### ISSUE TITLE
How to retrieve the User session after login

### ISSUE THREAD

**Issue by chrisvidal** [vdomah/oc-jwtauth#15]
Hi,
How to retrieve the User session after login?
I am building API using this plugin to handle the authentication.
How do I get the logged user session?
I tried the usual 

```
$user = Auth::getUser();
```

but it does not work

thanks

**Comment by vdomah** [comment]
From your question I see you need just User model instance not user's session. To achieve this you need to get user's id from token and then get the model:            
           

    $user_id = JWTAuth::authenticate($token)->id;
    // or
    $user_id = JWTAuth::parseToken()->authenticate()->id;
    // then
    $model = UserModel::findOrFail($user_id);

**Comment by chrisvidal** [comment]
ok thanks, I came up with
```php
$token = JWTAuth::parseToken()->getToken();
$user = JWTAuth::authenticate( $token );
```
