### ISSUE TITLE
php artisan jwt:generate does not work

### ISSUE THREAD

**Issue by mark-cobra** [vdomah/oc-jwtauth#19]
When I run the command I get this error

![image](https://user-images.githubusercontent.com/58164816/72712744-f0759a80-3b6b-11ea-84c1-00ea82d61170.png)

How can I fix this? Thanks

**Comment by mark-cobra** [comment]
I fixed it!
Change the method fire() to handle() within \vendor\tymon\jwt-auth\src\Commands\JWTGenerateCommand.php

**Comment by vdomah** [comment]
Thanks for reporting, but that's bad fix you're proposing. Here is related issue from the Laravel package repo: https://github.com/tymondesigns/jwt-auth/issues/1644
Should use:
````
php artisan jwt:secret
````
Need to test this

**Comment by alvaro-canepa** [comment]
This issued will be fixed updating tymon/jwt-auth to 1.0. 
But newest version has changes. Like class `\Tymon\JWTAuth\Providers\JWTAuthServiceProvider` that doesn't exists.
