### ISSUE TITLE
add others data in the reponse

### ISSUE THREAD

**Issue by taha-azzabi** [vdomah/oc-jwtauth#5]
Hello,

there is a way to add other data like user role in the header response , i know that i can modify directly the file route.php and add to 
`$user = [
            'id' => $userModel->id,
            'name' => $userModel->name,
            'surname' => $userModel->surname,
            'username' => $userModel->username,
            'email' => $userModel->email,
            'is_activated' => $userModel->is_activated,
        ];`

there is a way to extend this file , thans

**Comment by vdomah** [comment]
added this feature. Docs for instructions: https://github.com/vdomah/oc-jwtauth#how-to-define-own-set-of-user-attributes-in-response
