### ISSUE TITLE
Class jwt.auth does not exist

### ISSUE THREAD

**Issue by idpsycho** [vdomah/oc-jwtauth#8]
1. I have installed jwtauth plugin from october cms
2. Copied auth.php to root /config
3. In my own plugin, I have added routes.php with:
`  Route::post('api/test', function (\Request $request) {})->middleware('jwt.auth');`

I am getting error:
`  Class jwt.auth does not exist`
`  \vendor\laravel\framework\src\Illuminate\Container\Container.php `

It works fine when I replace it with the value from jwtauth/plugin.php boot():
`  // $this->app['router']->middleware('jwt.auth', '\Tymon\JWTAuth\Middleware\GetUserFromToken');`
`  ...->middleware('\Tymon\JWTAuth\Middleware\GetUserFromToken');`

Any ideas?

**Comment by richrosa** [comment]
I have the same problem. Doesn't look like it's registering globally.

**Comment by Adrion** [comment]
I had the same problem. I decided to use the registration method of the [documentation](https://octobercms.com/docs/plugin/registration#registering-middleware) 

inside boot() method: 

``` 
$this->app['Illuminate\Contracts\Http\Kernel']
            ->pushMiddleware('\Tymon\JWTAuth\Middleware\GetUserFromToken');

$this->app['Illuminate\Contracts\Http\Kernel']
            ->pushMiddleware('\Tymon\JWTAuth\Middleware\RefreshToken');
```

@vdomah any idea ? Or do you want a little PR for this ? :)

**Comment by vdomah** [comment]
Registering middleware globaly in October changed somehow after updating to L5.5 so now I suggest using ->middleware('\Tymon\JWTAuth\Middleware\GetUserFromToken'); as @idpsycho offered.

Changed README according to this.

Will update when find out the new way of global registration.
